#!/bin/bash

echo "🚀 Deploying CampusVibe Backend to Render"
echo "========================================"
echo ""
echo "📋 Follow these steps:"
echo ""
echo "1. Go to: https://render.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Select repository: karancoderg/CampusVibe"
echo "5. Configure:"
echo ""
echo "   Name: campusvibe-backend"
echo "   Environment: Node"
echo "   Root Directory: backend"
echo "   Build Command: npm install"
echo "   Start Command: npm start"
echo ""
echo "6. Add Environment Variables:"
echo "   NODE_ENV=production"
echo "   SUPABASE_URL=https://tefsuxgslyowilylcqtw.supabase.co"
echo "   SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZnN1eGdzbHlvd2lseWxjcXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTExMTYsImV4cCI6MjA3MjY4NzExNn0.pAFVoJgBBdnUnzST2nO-wSgSXB4juiv7oErcLlNpIaI"
echo "   SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZnN1eGdzbHlvd2lseWxjcXR3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzExMTExNiwiZXhwIjoyMDcyNjg3MTE2fQ.6v82VuPhy0KU01hom4AesZCx0JPOq_sfTy4icr_2vNg"
echo ""
echo "7. Click 'Create Web Service'"
echo ""
echo "✅ Your backend will be deployed at: https://campusvibe-backend.onrender.com"
echo ""
echo "🔗 After deployment, update your frontend API URL to the Render URL"
