#!/bin/bash

echo "🚀 CampusVibe Backend Deployment Guide"
echo "======================================"
echo ""
echo "Your backend is ready for deployment! Here are your options:"
echo ""
echo "📦 DEPLOYED URLS:"
echo "Vercel: https://backend-deploy-jb09jcl0z-karancodergs-projects.vercel.app"
echo ""
echo "⚠️  Note: Vercel deployment has authentication protection enabled."
echo "   You can disable it in your Vercel dashboard under Project Settings > Deployment Protection"
echo ""
echo "🔧 ALTERNATIVE DEPLOYMENT OPTIONS:"
echo ""
echo "1. 🌐 Render (Recommended for production):"
echo "   - Push your code to GitHub"
echo "   - Connect to https://render.com"
echo "   - Create new Web Service from your GitHub repo"
echo "   - Use these settings:"
echo "     Build Command: npm install"
echo "     Start Command: npm start"
echo "     Environment Variables:"
echo "       SUPABASE_URL=https://tefsuxgslyowilylcqtw.supabase.co"
echo "       SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZnN1eGdzbHlvd2lseWxjcXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTExMTYsImV4cCI6MjA3MjY4NzExNn0.pAFVoJgBBdnUnzST2nO-wSgSXB4juiv7oErcLlNpIaI"
echo "       SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZnN1eGdzbHlvd2lseWxjcXR3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzExMTExNiwiZXhwIjoyMDcyNjg3MTE2fQ.6v82VuPhy0KU01hom4AesZCx0JPOq_sfTy4icr_2vNg"
echo ""
echo "2. 🚂 Railway:"
echo "   - Visit https://railway.app"
echo "   - Connect your GitHub repo"
echo "   - Deploy automatically"
echo ""
echo "3. 🐳 Docker (for VPS/EC2):"
echo "   - Use the Dockerfile in your project"
echo "   - Deploy to any cloud provider"
echo ""
echo "✅ Your backend is working locally on http://localhost:3000"
echo "✅ Database connection is configured and working"
echo "✅ All environment variables are set up"
echo ""
echo "🔗 Next Steps:"
echo "1. Choose a deployment platform above"
echo "2. Update your frontend's API URL to point to the deployed backend"
echo "3. Test the deployment with the /health endpoint"
echo ""
echo "📝 Backend URL for frontend configuration:"
echo "   Replace 'http://localhost:3000' with your deployed URL"
